package:
    name: parafem
    version: 0.0.1

build:
    number: 5

source:
    path: ../

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ cdt('libxext') }}  # [linux]
        - ninja
        - cmake
    host:
        - python
        - pybind11
        - eigen
        - openmpi  # [unix]
        - vtk
        - tbb-devel
    run:
        - python
        - numpy
        - vtk

test:
    imports:
        - paraFEM

about:
    summary: explicit fem for membrane elements
